title: Sample input variable schema
schemaVersion: 1.0.0
version: "20190816"
locale: "en"
groupings:
- title: "Global Options"
  variables:
  - ${ssh_public_key}
  - ${ssh_private_key}
  - ${availability_domain}
- title: "HDP Options"
  variables:
  - ${ambari_version}
  - ${hdp_version}
  - ${hdp_utils_version}
  - ${cluster_name}
  - ${deployment_type}
- title: "Worker Node Options"
  variables:
  - ${worker_instance_shape}
  - ${worker_node_count}
  - ${block_volumes_per_worker}
- title: "HDFS Block Volume Size"
  variables:
  - ${data_blocksize_in_gbs}
  visible:
    not :
      - eq:
        - ${block_volumes_per_worker}
        - "0"
- title: "Master Node Options"
  variables:
  - ${master_instance_shape}
  - ${master_node_count}
  - ${nn_volume_size_in_gbs}
- title: "Utility Node Options"
  variables:
  - ${utility_instance_shape}
- title: "Edge Node Options"
  variables:
  - ${bastion_instance_shape}

- title: "Pre-Defined"
  variables:
  - ${region}
  - ${compartment_ocid}
  - ${tenancy_ocid}
  - ${InstanceImageOCID}
  - ${oci_service_gateway}
  visible: false

variables:
  ambari_version:
    type: enum
    enum:
    - "2.7.3"
    - "2.7.1"
    - "2.7.0"
    - "2.6.2.2"
    - "2.6.2"
    - "2.6.1.5"
    - "2.6.1"
    - "2.6.0"
    - "2.5.2"
    - "2.5.1"
    - "2.5.0.3"
    title: "Ambari Version"
    description: "Choose the version of Ambari to deploy"
    required: true

  hdp_version:
    type: enum
    enum:
    - "3.1.0.0"
    - "3.0.1.0"
    - "3.0.0.0"
    - "2.6.5.0"
    - "2.6.4.0"
    - "2.6.3.0"
    - "2.6.2.0"
    - "2.6.1.0"
    - "2.6.0.0"
    - "2.5.6.0"
    - "2.5.5.0"
    - "2.5.3.0"
    - "2.5.0.0"
    title: "HDP Version"
    description: "Choose the version of HDP to deploy"
    required: true

  hdp_utils_version:
    type: enum
    enum:
    - "1.1.0.22"
    - "1.1.0.21"
    - "1.1.0.20"
    title: "HDP Utils Version"
    description: "Choose the HDP Utils version to deploy"
    required: true

  cluster_name:
    type: string
    title: "Cluster Name"
    description: "Name your Cluster"
    required: true

  availability_domain:
    type: integer
    title: "Availability Domain"
    description: "Select AD"
    minimum: 1
    maximum: 3
    required: true

  deployment_type:
    type: enum
    enum:
    - "simple"
    - "secure"
    title: "Deployment Type"
    required: true

  worker_instance_shape:
    type: enum
    enum:
    - "VM.Standard2.8"
    - "VM.Standard2.16"
    - "VM.Standard2.24"
    - "BM.Standard2.52"
    - "VM.DenseIO2.8"
    - "VM.DenseIO2.16"
    - "VM.DenseIO2.24"
    - "BM.DenseIO2.52"
    title: "Shape of Worker Nodes"
    required: true

  worker_node_count:
    type: integer
    minimum: 3
    title: "Number of Worker Nodes"
    description: "3 is the minimum requirement"
    required: true

  master_instance_shape:
    type: enum
    enum:
    - "VM.Standard2.8"
    - "VM.Standard2.16"
    - "VM.Standard2.24"
    - "BM.Standard2.52"
    - "VM.DenseIO2.8"
    - "VM.DenseIO2.16"
    - "VM.DenseIO2.24"
    - "BM.DenseIO2.52"
    title: "Shape of Master Nodes"
    required: true

  master_node_count:
    type: integer
    minimum: 2
    title: "Number of Master Nodes"
    description: "2 is the minimum requirement"
    required: true

  utility_instance_shape:
    type: enum
    enum:
    - "VM.Standard2.8"
    - "VM.Standard2.16"
    - "VM.Standard2.24"
    - "BM.Standard2.52"
    - "VM.DenseIO2.8"
    - "VM.DenseIO2.16"
    - "VM.DenseIO2.24"
    - "BM.DenseIO2.52"
    title: "Shape of Utility Node"
    required: true

  bastion_instance_shape:
    type: enum
    enum:
    - "VM.Standard2.1"
    - "VM.Standard2.2"
    - "VM.Standard2.4"
    - "VM.Standard2.8"
    - "VM.Standard2.16"
    - "VM.Standard2.24"
    - "BM.Standard2.52"
    - "VM.DenseIO2.8"
    - "VM.DenseIO2.16"
    - "VM.DenseIO2.24"
    - "BM.DenseIO2.52"
    title: "Shape of Edge Nodes"
    required: true

  ssh_public_key:
    type: string
    title: "SSH Public Key"
    description: "Copy/Paste the contents of your SSH Public Key"
    required: true

  ssh_private_key:
    type: string
    title: "SSH Private Key"
    description: "Copy/Paste the contents of your SSH Private Key"
    required: true

  data_blocksize_in_gbs:
    type: integer
    title: "HDFS Block Volume Size ( GB )"
    description: "700 to 32,768 "
    minimum: 700
    maximum: 32768
    required: true

  block_volumes_per_worker:
    type: integer
    title: "Number of Block Volumes for HDFS"
    description: "0 to 29"
    minimum: 0
    maximum: 29
    required: true

  nn_volume_size_in_gbs:
    type: integer
    title: "Block Volume Size for NameNode Metadata"
    description: "500 to 32,768 "
    minimum: 500
    maximum: 32768
    required: true